name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libtool autoconf automake pkg-config libffi-dev libssl-dev openjdk-17-jdk unzip zip
          pip install buildozer "cython<3.0" virtualenv
      - name: Build
        run: |
          yes | buildozer -v android debug
      - name: Save
        uses: actions/upload-artifact@v4
        with:
          name: OrionAPK
          path: bin/*.apk
