name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libtool autoconf automake pkg-config \
          libffi-dev libssl-dev openjdk-17-jdk unzip zip
          pip install --upgrade buildozer cython==0.29.33 virtualenv

      - name: Build with Buildozer
        run: |
          yes | buildozer -v android debug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Orion-Explorer-APK
          path: bin/*.apk
